- name: Set path secure order
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Set path secure order Profile
      replace:
        dest: /etc/profile
        regexp: '(\/usr\/local\/sbin:\/usr\/local\/bin):(\/usr\/sbin:\/usr\/bin):(\/sbin:\/bin)'
        replace: '\2:\3:\1'
    - name: Set path secure order Profile
      replace:
        dest: /etc/profile
        regexp: '(\/usr\/local\/bin):(\/usr\/bin):(\/bin)'
        replace: '\2:\3:\1'
    - name: Set path secure order Sudoers
      replace:
        dest: /etc/sudoers
        regexp: '(\/usr\/local\/sbin:\/usr\/local\/bin):(\/usr\/sbin:\/usr\/bin):(\/sbin:\/bin)'
        replace: '\2:\3:\1'
